name: marketplace-api-412-dev
services:
  goods-api:
    image: goods-api-412-dev
    build:
      context: .
      dockerfile: GoodsApi/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "5033:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
