events {}

http {
    upstream products_api {
        server products-api:8080;
    }
    
    upstream purchases_api {
        server purchases-api:8080;
    }
    
    server {
        listen 80;
        
        location ~ ^/api/products?(/|$) {
            proxy_pass http://products_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real_IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
       
        }
        
        location /api/purchases {
            proxy_pass http://purchases_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real_IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
       
        }
        
        location /swagger/products/ {
            proxy_pass http://products_api/swagger/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /swagger/purchases/ {
            proxy_pass http://purchases_api/swagger/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}